name: ev_spot_flutter
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.2
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  google_maps_flutter: ^2.3.1
  geolocator: ^11.0.0
  shared_preferences: ^2.2.1

  # for MobX State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mapStyles/

